### ISSUE TITLE
derod crash

### ISSUE THREAD

**Issue by bn999** [deroproject/derohe#2]
Console:

DERO HE: 1897/1992 [1895/1989] P 6 TXp 0:0 NW 1.1 KH/s > TESTNET>> sync_info
Connection info for peers
Remote Addr          PEER ID          PORT   State  Latency               H/T DIR QUEUE      IN     OUT  IN SPEED  OUT SPEED    Version
190.2.135.219        d22d3095be9b1ccd 40401  ACTIVE    62ms         1895/1989 OUT     0  1.5 MB  239 kB    10 kB      62 B     3.0.0-10.DEROHE.alph 
212.8.242.60         af141763b7bb9392 40401  ACTIVE   929ms         1895/1989 OUT     0  1.1 MB  238 kB   9.2 kB      62 B     3.0.0-10.DEROHE.alph 
212.8.250.158        f3a803820c211a94 40401  ACTIVE     4ms         1895/1989 OUT     0  1.1 MB  298 kB   6.6 kB      62 B     3.0.0-10.DEROHE.alph 
52.136.112.140       d1bf5b01af3c6b3c 40401  ACTIVE   904ms         1895/1989 OUT     0  1.2 MB  298 kB   7.7 kB      62 B     3.0.0-10.DEROHE.alph 
67.205.145.73        5d810f79bdbaa9e0 40401  ACTIVE  1.079s         1895/1989 OUT     0  1.0 MB  298 kB   6.7 kB      62 B     3.0.0-10.DEROHE.alph 
85.217.170.60        4206c9ced097c2da 40401  ACTIVE  1.492s         1895/1989 OUT     0  622 kB  325 kB   2.9 kB      62 B     3.0.0-10.DEROHE.alph 
WARN[0445] fError deserialiing block, block id bda4dc6b8c6b37b638520f2c46fc5e1be48fcedc04dc8f69263dd405d8265b63 len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
DERO HE: 1897/1992 [1895/1989] P 6 TXp 0:0 NW 1.1 KH/s > TESTNET>> panic: Block Header could not be parsed Invalid Major Version in Block

goroutine 64 [running]:
github.com/deroproject/derohe/blockchain.(*Blockchain).Calculate_Height_At_Tips(0xc00052c0f0, 0xc0002ea000, 0x4, 0x4, 0xc0009602e8)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/store.go:188 +0xff
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty_At_Tips(0xc00052c0f0, 0xc0002ea000, 0x4, 0x4, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/difficulty.go:175 +0x1a3
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty(0xc00052c0f0, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1039 +0x39
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Network_HashRate(...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1053
main.main.func4(0xc00052c0f0, 0xc0003a2ec0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:313 +0x317
created by main.main
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:254 +0x9b7

derod.log:

2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="85.217.170.60:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="212.8.250.158:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="67.205.145.73:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="52.136.112.140:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="212.8.250.158:40401" com=P2P
 
2020-12-20T17:41:36-05:00 DEBUG    : Mining block will give reward to deto1qxqzvxue5y9mk9shw3sspj6kpc5tc7w8c330dtqlgyzr2skyq0p930q8gagzv
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="67.205.145.73:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Chain extended but height is same 1897 blid 8deda124f698e75f5b942e727ad951251a677e11e186ad83eecdb591dcd807d0
2020-12-20T17:41:36-05:00 INFO     : Full order [a4da32724910c5feef49d571d7eb6777704fc53c5889e5b898b05b06b4fb39c6 ecce142b5e250d92e2df67855e083142eaca52e960cce788fb6763d821205bbc 5d2dfd4b825a6f9faac7135d86fc0b055e3784b38fc70684f8c957d7f310fbf6 7477fb0f4b5f2f515b9bd2d52d93a9f5785e2f38fd0dfeac36da9c29d96f2b9a 796aa3c242463b2143d70cc2cde707ac33c53e319a973e3477903ed92ba832bf 52190517a2d70c8b8a3cbf5f70ac8d26ba4cd759c250fc0a0da00fbce2a206e0 8263ede49bc1087d338d683fd523e3af49a32248a4170a2864d48eae89961a11 c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a 525638fee32c777506b6268c203801016ef9bb1da2e9224ed59a06da25fa0504 34705d71bbf0cc52b3de88f6005f9dd0ad3653c59ea1dd8a6c5c55d0a4781741] base a4da32724910c5feef49d571d7eb6777704fc53c5889e5b898b05b06b4fb39c6 base topo pos 1983
2020-12-20T17:41:36-05:00 INFO     : New tips(after adding 8deda124f698e75f5b942e727ad951251a677e11e186ad83eecdb591dcd807d0) map[251b2a01fcf44c5fdd19dc1086081b27ad4e186ee52c5ba1cc39c2fea5b8fb7a:251b2a01fcf44c5fdd19dc1086081b27ad4e186ee52c5ba1cc39c2fea5b8fb7a 34705d71bbf0cc52b3de88f6005f9dd0ad3653c59ea1dd8a6c5c55d0a4781741:34705d71bbf0cc52b3de88f6005f9dd0ad3653c59ea1dd8a6c5c55d0a4781741 8deda124f698e75f5b942e727ad951251a677e11e186ad83eecdb591dcd807d0:8deda124f698e75f5b942e727ad951251a677e11e186ad83eecdb591dcd807d0 bda4dc6b8c6b37b638520f2c46fc5e1be48fcedc04dc8f69263dd405d8265b63:bda4dc6b8c6b37b638520f2c46fc5e1be48fcedc04dc8f69263dd405d8265b63]
2020-12-20T17:41:36-05:00 INFO     : Block successfully acceppted by chain 8deda124f698e75f5b942e727ad951251a677e11e186ad83eecdb591dcd807d0
2020-12-20T17:41:36-05:00 INFO     : Broadcasted block 8deda124f698e75f5b942e727ad951251a677e11e186ad83eecdb591dcd807d0 to 5 peers
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash 8deda124f698e75f5b942e727ad951251a677e11e186ad83eecdb591dcd807d0 level=debug DIR=OUT RIP="212.8.242.60:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="52.136.112.140:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="85.217.170.60:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="212.8.250.158:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="67.205.145.73:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="52.136.112.140:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="52.136.112.140:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : Incoming block Notification hash c929aa435185ef4da0bb12cddb968c57f92f72b19bac13089457f5cef1369c8a level=debug DIR=OUT RIP="212.8.250.158:40401" com=P2P
 
2020-12-20T17:41:36-05:00 INFO     : level=warning msg="fError deserialiing block, block id bda4dc6b8c6b37b638520f2c46fc5e1be48fcedc04dc8f69263dd405d8265b63 len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block\n\n" com=CORE
2020-12-20T17:41:36-05:00 INFO     : Chain extended but height is same 1897 blid bda4dc6b8c6b37b638520f2c46fc5e1be48fcedc04dc8f69263dd405d8265b63

**Comment by CaptainDero** [comment]
Noted.

**Comment by bn999** [comment]
Seems it happens from time to time:

INFO[8452] Block 393dde30c3d3816ca31e7994a710d5a36c37fa6eb5368ffa0d864bd8079d7901 successfully accepted at height 2333, Notifying Network  com=CORE
INFO[8452] Submitted block 393dde30c3d3816ca31e7994a710d5a36c37fa6eb5368ffa0d864bd8079d7901 accepted  com=RPC
WARN[8452] Block f58063e832fd07be696f2113c51b84ccf92a67ad38cc66e3b09d9125f0f02dbf rejected by chain due to duplicate hwork.  com=CORE
INFO[8452] Submitting block f58063e832fd07be696f2113c51b84ccf92a67ad38cc66e3b09d9125f0f02dbf err Error duplicate work  com=RPC
INFO[8529] Block c18bfb73b103e6479540e02528862b4e7e0ae0d2d1749e687648e4030b01f1ce successfully accepted at height 2334, Notifying Network  com=CORE
INFO[8529] Submitted block c18bfb73b103e6479540e02528862b4e7e0ae0d2d1749e687648e4030b01f1ce accepted  com=RPC
INFO[8536] Block 0a9aa418ee71dd84682f253c4672df248c067a10bf56f9bb14ca8d4e0a65c22b successfully accepted at height 2335, Notifying Network  com=CORE
INFO[8536] Submitted block 0a9aa418ee71dd84682f253c4672df248c067a10bf56f9bb14ca8d4e0a65c22b accepted  com=RPC
INFO[8539] Block 8fa080edab9554dac368c7ad55497a97fb3f531bdc5b536addd9ce6d7ff62b64 successfully accepted at height 2336, Notifying Network  com=CORE
INFO[8539] Submitted block 8fa080edab9554dac368c7ad55497a97fb3f531bdc5b536addd9ce6d7ff62b64 accepted  com=RPC
WARN[8714] Rejecting Block, timestamp is too much into future, make sure that system clock is correct  blid=039e8e39519745978c72450c6a3bc38e05777e49cabc6da9bd284c63a568554a com=CORE
WARN[8714] We must have queued 692c9ed4e747601e0a962af65aeb9bcd07cfab6fe4c826be9770f53ccb670a0a, but we skipped it at height 2339  com=P2P
INFO[8763] Block 3ab6ba7d74a2a59cb2cea4313e5a130acfd34aa2a36fc52a80b3b6d31b8facdc successfully accepted at height 2341, Notifying Network  com=CORE
INFO[8763] Submitted block 3ab6ba7d74a2a59cb2cea4313e5a130acfd34aa2a36fc52a80b3b6d31b8facdc accepted  com=RPC
INFO[8799] Block 43ceed25203a12dd1d866c25e62dcb82e853f4cffdee9c802273bcf9cd92735a successfully accepted at height 2342, Notifying Network  com=CORE
INFO[8799] Submitted block 43ceed25203a12dd1d866c25e62dcb82e853f4cffdee9c802273bcf9cd92735a accepted  com=RPC
INFO[8846] Block c23d21abb7468a47b81055dc40beae06f79c1f6ad38cea6c80f1d6acb501730d successfully accepted at height 2343, Notifying Network  com=CORE
INFO[8846] Submitted block c23d21abb7468a47b81055dc40beae06f79c1f6ad38cea6c80f1d6acb501730d accepted  com=RPC
INFO[8880] Block 86d049a0cb3c00e4a61550d80908eb596e1f2c904cdfb64233aed96adc4b26d9 successfully accepted at height 2346, Notifying Network  com=CORE
INFO[8880] Submitted block 86d049a0cb3c00e4a61550d80908eb596e1f2c904cdfb64233aed96adc4b26d9 accepted  com=RPC
INFO[8953] Block c81c582262614c9711375b429f4875957f41cd8da5ff164897171553e5336408 successfully accepted at height 2347, Notifying Network  com=CORE
INFO[8953] Submitted block c81c582262614c9711375b429f4875957f41cd8da5ff164897171553e5336408 accepted  com=RPC
INFO[8983] Block 91964b485cd805e600a93af383881d7a78134f8594b01fc47fbaae9ab32b1932 successfully accepted at height 2349, Notifying Network  com=CORE
INFO[8983] Submitted block 91964b485cd805e600a93af383881d7a78134f8594b01fc47fbaae9ab32b1932 accepted  com=RPC
INFO[9039] Block 52212fc68c8d71025847c6ae64a14d7322bfed183f9101dc33d32909e5087b12 successfully accepted at height 2350, Notifying Network  com=CORE
INFO[9039] Submitted block 52212fc68c8d71025847c6ae64a14d7322bfed183f9101dc33d32909e5087b12 accepted  com=RPC
INFO[9099] Block 5bcb70362b6ff4bca902cffb16765d065784df31caf8282ecbb31026a5f2cb66 successfully accepted at height 2351, Notifying Network  com=CORE
INFO[9099] Submitted block 5bcb70362b6ff4bca902cffb16765d065784df31caf8282ecbb31026a5f2cb66 accepted  com=RPC
INFO[9136] Block 13fdaaf4c2a822096527b2fed7738021cb322edcee7182f87e2b2faeb0ecf240 successfully accepted at height 2352, Notifying Network  com=CORE
INFO[9136] Submitted block 13fdaaf4c2a822096527b2fed7738021cb322edcee7182f87e2b2faeb0ecf240 accepted  com=RPC
INFO[9139] Block e9972dc5409eb2ffb374757481dbde142d53864158b1bc9ffec2d25eb21b07e2 successfully accepted at height 2353, Notifying Network  com=CORE
INFO[9139] Submitted block e9972dc5409eb2ffb374757481dbde142d53864158b1bc9ffec2d25eb21b07e2 accepted  com=RPC
INFO[9164] Block bc9b3741f939d6f79e46b4f194e6c1e3655797fb0c21234f39b9ae69e0937383 successfully accepted at height 2354, Notifying Network  com=CORE
INFO[9164] Submitted block bc9b3741f939d6f79e46b4f194e6c1e3655797fb0c21234f39b9ae69e0937383 accepted  com=RPC
INFO[9174] Block 445254f8bfe81a06036e6ec9f03b2caf56e7259853c06ab7e572a1048f6e3b81 successfully accepted at height 2355, Notifying Network  com=CORE
INFO[9174] Submitted block 445254f8bfe81a06036e6ec9f03b2caf56e7259853c06ab7e572a1048f6e3b81 accepted  com=RPC
INFO[9269] Block 091e519263862eb3f8caf010c400f3f9e7ab8389c103f4b957d49251a0f96a90 successfully accepted at height 2357, Notifying Network  com=CORE
INFO[9269] Submitted block 091e519263862eb3f8caf010c400f3f9e7ab8389c103f4b957d49251a0f96a90 accepted  com=RPC
INFO[9410] Block 7206501ac99f51ff62fa1fd0ab58f036b0918ef112e5d25ad4543de144244cbf successfully accepted at height 2359, Notifying Network  com=CORE
INFO[9410] Submitted block 7206501ac99f51ff62fa1fd0ab58f036b0918ef112e5d25ad4543de144244cbf accepted  com=RPC
INFO[9423] Block 5b290f3942a15d52b3d816a9135e1c3ddc5236f706412be0ff2742965e5096b2 successfully accepted at height 2361, Notifying Network  com=CORE
INFO[9423] Submitted block 5b290f3942a15d52b3d816a9135e1c3ddc5236f706412be0ff2742965e5096b2 accepted  com=RPC
INFO[9448] Block fb682ee13b81068a82f4933b24df64634b10ed4f662e1f12b469b70a9f18c532 successfully accepted at height 2362, Notifying Network  com=CORE
INFO[9448] Submitted block fb682ee13b81068a82f4933b24df64634b10ed4f662e1f12b469b70a9f18c532 accepted  com=RPC
INFO[9452] Block 0f50ebef6bab6203c7bea08ed458adaa92ea8bee94b2c7cb580e89071963b0a7 successfully accepted at height 2363, Notifying Network  com=CORE
INFO[9452] Submitted block 0f50ebef6bab6203c7bea08ed458adaa92ea8bee94b2c7cb580e89071963b0a7 accepted  com=RPC
INFO[9586] Block 83473f2cc4e34127340ad4212bf384a921d24a38fa24cd71b3814a01b23d800c successfully accepted at height 2364, Notifying Network  com=CORE
INFO[9586] Submitted block 83473f2cc4e34127340ad4212bf384a921d24a38fa24cd71b3814a01b23d800c accepted  com=RPC
WARN[9595] fError deserialiing block, block id 83473f2cc4e34127340ad4212bf384a921d24a38fa24cd71b3814a01b23d800c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
DERO HE: 2365/2498 [2363/2495] P 12 TXp 0:0 NW 2.2 KH/s > TESTNET>> panic: Block Header could not be parsed Invalid Major Version in Block



goroutine 76 [running]:
github.com/deroproject/derohe/blockchain.(*Blockchain).Calculate_Height_At_Tips(0xc0006f25a0, 0xc00087f4c0, 0x2, 0x2, 0xc000a0a780)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/store.go:188 +0xff
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty_At_Tips(0xc0006f25a0, 0xc00087f4c0, 0x2, 0x2, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/difficulty.go:175 +0x1a3
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty(0xc0006f25a0, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1039 +0x39
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Network_HashRate(...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1053
main.main.func4(0xc0006f25a0, 0xc000287aa0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:313 +0x317
created by main.main
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:254 +0x9b7
$

**Comment by CaptainDero** [comment]
Can you compress and upload your blockchain testnet folder.

**Comment by bn999** [comment]
Attached.
[testnet.tar.gz](https://github.com/deroproject/derohe/files/5724945/testnet.tar.gz)

**Comment by CaptainDero** [comment]
Delete old testnet folder and update binaries to latest release 3.

**Comment by bn999** [comment]
Much better

**Comment by CaptainDero** [comment]
Please discuss StarGate testnet  issues [here](https://github.com/deroproject/derohe/issues/3).
