### ISSUE TITLE
RPC methods do not properly handle / validate invalid inputs

### ISSUE THREAD

**Issue by mukatee** [deroproject/derohe#22]
# Summary

Both Wallet and Daemon RPC interfaces seem to lack proper input validation. I tried a few broken JSON inputs and it gives either 500 Server Error, or 200 OK with a stacktrace in the body. Neither should be expected but rather give some suitable error code such as 400 Bad Request with some details on error if available.

Following are just a few quick examples I tried, I expect all methods and inputs should be checked.

# Daemon RPC Examples

Examples for daemon RPC (listening on localhost:9999):

missing parameters:

`
curl -v -X POST  http://localhost:9999/json_rpc  -d  '{"jsonrpc": "2.0", "id":"0", "method": "getgasestimate"}' -H 'content-type: application/json'`

```
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /json_rpc HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.68.0
> Accept: */*
> content-type: application/json
> Content-Length: 56
> 
* upload completely sent off: 56 out of 56 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 2179
< Content-Type: application/json
< Date: Sun, 30 Jan 2022 22:08:07 GMT
< 

{"jsonrpc":"2.0","id":"0","error":{"code":-32098,"message":"panic occured. stack trace r interface conversion: interface {} is nil, not uint64 goroutine 12820 [running]:\nruntime/debug.Stack()\n\t/snap/go/9028/src/runtime/debug/stack.go:24 +0x65\ngithub.com/deroproject/derohe/cmd/derod/rpc.GetGasEstimate.func1()\n\t/root/derohe/cmd/derod/rpc/rpc_dero_estimategas.go:42 +0x45\npanic({0x9c34c0, 0xc001f77ef0})\n\t/snap/go/9028/src/runtime/panic.go:1038 +0x215\ngithub.com/deroproject/derohe/dvm.(*Simulator).RunSC(0xc001f77e60, 0x3736, {0x0, 0x0, 0x0}, 0x34f2, 0xc00353fe17)\n\t/root/derohe/dvm/simulator.go:126 +0x758\ngithub.com/deroproject/derohe/cmd/derod/rpc.GetGasEstimate({0xc0000b35d0, 0x465b0d}, {{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, ...})\n\t/root/derohe/cmd/derod/rpc/rpc_dero_estimategas.go:79 +0x44b\nreflect.Value.call({0x9b5b20, 0xada180, 0xc0002ded18}, {0xa52249, 0x4}, {0xc001f77dd0, 0x2, 0xc00253ad28})\n\t/snap/go/9028/src/reflect/value.go:556 +0x845\nreflect.Value.Call({0x9b5b20, 0xada180, 0xc001f77da0}, {0xc001f77dd0, 0x2, 0x2})\n\t/snap/go/9028/src/reflect/value.go:339 +0xc5\ngithub.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func10({0xb85840, 0xc001f77da0}, 0xf3d270)\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/handler/handler.go:233 +0xed\ngithub.com/creachadair/jrpc2/handler.Func.Handle(0xf3d270, {0xb85840, 0xc001f77da0}, 0x1)\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/handler/handler.go:24 +0x2f\ngithub.com/creachadair/jrpc2.(*Server).invoke(0xc0003ec000, {0xb85798, 0xc002dec700}, {0xb78f20, 0xc00037f420}, 0xc002dec6c0)\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:350 +0x17e\ngithub.com/creachadair/jrpc2.(*Server).dispatch.func1.1()\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:229 +0xbe\ngithub.com/creachadair/jrpc2.(*Server).dispatch.func1()\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:234 +0x17d\ngithub.com/creachadair/jrpc2.(*Server).serve.func1()\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:155 +0x5a\nc* Connection #0 to host localhost left intact
reated by github.com/creachadair/jrpc2.(*Server).serve\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:153 +0x29\n"}}
```

extra curly brace:
`curl -v -X POST  http://localhost:9999/json_rpc  -d  '{"jsonrpc": "2.0", "id":"0", "method": "getheight"}}' -H 'content-type: application/json'
`

```
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST /json_rpc HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.68.0
> Accept: */*
> content-type: application/json
> Content-Length: 52
> 
* upload completely sent off: 52 out of 52 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Sun, 30 Jan 2022 22:06:54 GMT
< Content-Length: 31
< Content-Type: text/plain; charset=utf-8
< 
[-32700] invalid request value

```

# Wallet RPC Examples

Examples for Wallet RPC (listening on localhost:40003):

Missing parameters / parameters in wrong place:

`curl -v -X POST  http://localhost:40003/json_rpc  -d  '{"jsonrpc": "2.0", "id":"0", "method": "transfer", "params": {"burn": 0, "amount": 100, "destination": "deto1qy0qygek8vm9qumxmttxv2us3ztrpd0nt5f3ejzreq2y3ep8m602cqg774elx"}' -H 'content-type: application/json'`
```

* Connected to localhost (127.0.0.1) port 40003 (#0)
> POST /json_rpc HTTP/1.1
> Host: localhost:40003
> User-Agent: curl/7.68.0
> Accept: */*
> content-type: application/json
> Content-Length: 172
> 
* upload completely sent off: 172 out of 172 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Sun, 30 Jan 2022 22:18:32 GMT
< Content-Length: 31
< Content-Type: text/plain; charset=utf-8
< 
[-32700] invalid request value
```

Extra curly:

`curl -v -X POST  http://localhost:30003/json_rpc  -d  '{"jsonrpc": "2.0", "id":"0", "method": "transfer", "params": {"burn": 0, "amount": 100, "destination": "deto1qy0qygek8vm9qumxmttxv2us3ztrpd0nt5f3ejzreq2y3ep8m602cqg774elx"}}' -H 'content-type: application/json'
`

```
* Connected to localhost (127.0.0.1) port 40003 (#0)
> POST /json_rpc HTTP/1.1
> Host: localhost:40003
> User-Agent: curl/7.68.0
> Accept: */*
> content-type: application/json
> Content-Length: 173
> 
* upload completely sent off: 173 out of 173 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 2157
< Content-Type: application/json
< Date: Sun, 30 Jan 2022 22:16:50 GMT
< 
{"jsonrpc":"2.0","id":"0","error":{"code":-32098,"message":"panic occured. stack trace goroutine 47 [running]:\nruntime/debug.Stack()\n\t/snap/go/9028/src/runtime/debug/stack.go:24 +0x65\ngithub.com/deroproject/derohe/walletapi/rpcserver.Transfer.func1()\n\t/root/derohe/walletapi/rpcserver/rpc_transfer.go:36 +0x35\npanic({0x7cf900, 0xc000364360})\n\t/snap/go/9028/src/runtime/panic.go:1038 +0x215\ngithub.com/deroproject/derohe/walletapi.(*Wallet_Memory).TransferPayload0(0xc0003f0000, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x2, 0x0}, 0x0, ...)\n\t/root/derohe/walletapi/wallet_transfer.go:233 +0x30e5\ngithub.com/deroproject/derohe/walletapi/rpcserver.Transfer({0x8ae060, 0xc0004d7560}, {{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, ...})\n\t/root/derohe/walletapi/rpcserver/rpc_transfer.go:69 +0x7b7\nreflect.Value.call({0x7924e0, 0x830ce8, 0xc00023fd18}, {0x7f2c84, 0x4}, {0xc0004d7830, 0x2, 0xc0003e0528})\n\t/snap/go/9028/src/reflect/value.go:556 +0x845\nreflect.Value.Call({0x7924e0, 0x830ce8, 0xc0004d7560}, {0xc0004d7830, 0x2, 0x2})\n\t/snap/go/9028/src/reflect/value.go:339 +0xc5\ngithub.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func10({0x8ae060, 0xc0004d7560}, 0xb771e0)\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/handler/handler.go:233 +0xed\ngithub.com/creachadair/jrpc2/handler.Func.Handle(0xb771e0, {0x8ae060, 0xc0004d7560}, 0x1)\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/handler/handler.go:24 +0x2f\ngithub.com/creachadair/jrpc2.(*Server).invoke(0xc0000de000, {0x8adfb8, 0xc000065440}, {0x8a5ea0, 0xc00036a480}, 0xc000065400)\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:350 +0x17e\ngithub.com/creachadair/jrpc2.(*Server).dispatch.func1.1()\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:229 +0xbe\ngithub.com/creachadair/jrpc2.(*Server).dispatch.func1()\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:234 +0x17d\ngithub.com/creachadair/jrpc2.(*Server).serve.func1()\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:155 +0x5a\ncreated by github.com/c* Connection #0 to host localhost left intact
reachadair/jrpc2.(*Server).serve\n\t/root/derohe/vendor/github.com/creachadair/jrpc2/server.go:153 +0x29\n"}}

```

**Comment by CaptainDero** [comment]
Noted.
