### ISSUE TITLE
DERO:>>> panic: Invalid Major Version in Block

### ISSUE THREAD

**Issue by jgonzis** [deroproject/derohe#57]
Why after ver 78 I have that error. not in 1 Node I have it in 2...

**Comment by jgonzis** [comment]
DERO:>>> panic: Invalid Major Version in Block


goroutine 12 [running]:
github.com/deroproject/derohe/blockchain.(*Blockchain).Load_Block_Timestamp(0x403571, {0xb3, 0xe2, 0x93, 0xf0, 0x53, 0xe9, 0x90, 0x7d, 0xc7, ...})
	/usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/store.go:157 +0x51
github.com/deroproject/derohe/blockchain.Get_Difficulty_At_Tips({0xb89b78, 0xc0004ae160}, {0xc00053a700, 0x1, 0x1})
	/usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/difficulty.go:234 +0x48f
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty_At_Tips(0xc0004ae160, {0xc00053a700, 0x1, 0x1})
	/usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/difficulty.go:146 +0x18f
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty(0xc0004ae160)
	/usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1152 +0x31
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Network_HashRate(...)
	/usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1156
main.main.func3()
	/usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:306 +0x385
created by main.main
	/usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:267 +0x13cf

> please paste the full error
