### ISSUE TITLE
GetGasEstimate - stack trace r Bucket cannot start with ':' goroutine

### ISSUE THREAD

**Issue by g45t345rt** [deroproject/derohe#78]
Sometimes I get this error when using `GetGasEstimate` before installing a smart contract.

```
-32098:panic occured. stack trace r Bucket cannot start with ':' goroutine 1202031 [running]:
runtime/debug.Stack()
        /home/github/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/deroproject/derohe/cmd/derod/rpc.GetGasEstimate.func1()
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/rpc/rpc_dero_estimategas.go:42 +0x45
panic({0x698b00, 0xc02edbcb80})
        /home/github/local/go/src/runtime/panic.go:1038 +0x215
github.com/deroproject/derohe/dvm.Wrapped_tree(0x9e36b0847c8714d8, 0x1dedba9dc7a5a6c, {0x3a, 0x93, 0x9e, 0x96, 0x2f, 0x9, 0xae, 0xfc, ...})
        /usr/home/github/gowork/src/github.com/deroproject/derohe/dvm/sc.go:113 +0x165
github.com/deroproject/derohe/dvm.(*Simulator).SCInstall(0xc013f84240, {0xc0eb3dca80, 0x9f1}, 0x1, {0xc0ec02bd40, 0x1, 0x4}, 0xc0e8cdb308, 0x2085fd)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/dvm/simulator.go:107 +0x1ee
github.com/deroproject/derohe/cmd/derod/rpc.GetGasEstimate({0xc0e8cdb658, 0x14542d}, {{0x0, 0x0, 0x0}, {0xc0eb3dca80, 0x9f1}, 0x0, {0x0, 0x0}, ...})
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/rpc/rpc_dero_estimategas.go:75 +0x39e
reflect.Value.call({0x69f040, 0x7c4db0, 0xc0e8cdbda0}, {0x73b380, 0x4}, {0xc013f84150, 0x2, 0xc0eb257db0})
        /home/github/local/go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x69f040, 0x7c4db0, 0xc013f84030}, {0xc013f84150, 0x2, 0x2})
        /home/github/local/go/src/reflect/value.go:339 +0xc5
github.com/creachadair/jrpc2/handler.(*FuncInfo).Wrap.func10({0x8730a0, 0xc013f84030}, 0xc59490)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/vendor/github.com/creachadair/jrpc2/handler/handler.go:244 +0xed
github.com/creachadair/jrpc2/handler.Func.Handle(0xc59490, {0x8730a0, 0xc013f84030}, 0x1)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/vendor/github.com/creachadair/jrpc2/handler/handler.go:25 +0x2f
github.com/creachadair/jrpc2.(*Server).invoke(0xc0001262a0, {0x872ff8, 0xc036601180}, {0x866a60, 0xc00017ae60}, 0xc036601140)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/vendor/github.com/creachadair/jrpc2/server.go:379 +0x17e
github.com/creachadair/jrpc2.(*Server).dispatch.func1()
        /usr/home/github/gowork/src/github.com/deroproject/derohe/vendor/github.com/creachadair/jrpc2/server.go:230 +0x1b1
github.com/creachadair/jrpc2.(*Server).serve.func1()
        /usr/home/github/gowork/src/github.com/deroproject/derohe/vendor/github.com/creachadair/jrpc2/server.go:152 +0x5a
created by github.com/creachadair/jrpc2.(*Server).serve
        /usr/home/github/gowork/src/github.com/deroproject/derohe/vendor/github.com/creachadair/jrpc2/server.go:150 +0x29
```

**Comment by CaptainDero** [comment]
Done, will be there in next release.
